online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('users/', include("users.urls", namespace="users")),
    path('products/', include("products.urls", namespace="products")),

    
    
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)


    )

products/urls.py
from django.urls import path

from products import views


app_name = "products"

urlpatterns = [
    path('create-product/', views.create_product, name='create_product'),
    path('edit-product/<int:id>/', views.edit_product, name='edit_product'),
    path('delete-product/<int:id>/', views.delete_product, name='delete_product'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),

]

users/urls.py
from users import views
from django.urls import path


app_name = "users"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('admin-login/', views.admin_login, name="admin_login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),

]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('admin-view/', views.admin_view, name="admin_view"),

]

templates/includes/header.html
{% load static %}
<header>
    <h1>
        <a href="{% url 'web:index' %}">
            <img
                src="{% static 'assets/images/onlinestore.png' %}"
                alt="Logo"
                style="width:25% ;"
            />
        </a>
    </h1>
    <div>
        {% if request.user.is_staff %}
        <a href="{% url 'products:create_product' %}" class="btn btn-dark">Create</a> 
        <a href="{%url 'users:logout' %}" class="btn btn-danger"> Logout </a>
        {% endif %}
        {% if request.user.is_authenticated and not request.user.is_staff %}
        <h6>{{request.user}}</h6>
        <a href="{% url 'products:view_cart' %}" class="btn btn-dark"> Cart </a>
        <a href="{%url 'users:logout' %}" class="btn btn-danger"> Logout </a>
        {% else %}
        {% if not request.user.is_staff %}
        <a href="{%url 'users:login' %}" class="btn btn-success"> Login </a>
        {% endif %}
        {% endif %} 

    <div>
</header>