online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('users/', include("users.urls", namespace="users")),
    path('products/', include("products.urls", namespace="products")),

    
    
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)


    )

products/urls.py
from django.urls import path

from products import views


app_name = "products"

urlpatterns = [
    path('create-product/', views.create_product, name='create_product'),
    path('edit-product/<int:id>/', views.edit_product, name='edit_product'),
    path('delete-product/<int:id>/', views.delete_product, name='delete_product'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),

]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('admin-view/', views.admin_view, name="admin_view"),

]

templates/admin_home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="wrapper">
    <!-- {% include 'includes/header.html' %} -->
    <div class="container">
        {% for instance in instances %}
        <div class="card" style="width: 18rem">
            <img class="card-img-top" src="{{instance.image.url}}" alt="Card image cap" />
            <div class="card-body">
                <h4 class="card-title">{{instance.name}}</h4>
                <h6 class="card-text">INR{{instance.price}}</h6>
                <a href="{% url 'products:edit_product'  id=instance.id %}" class="btn btn-primary">Edit</a>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <title>{{title}}</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
        <link
            rel="stylesheet"
            href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        />
        <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="{% static 'images/icons/fyk.png' %}"
        />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta property="og:image" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
    </head>
    <body>
        
        {% block content %} {% endblock %}
        <script
            src="https://code.jquery.com/jquery-3.7.0.min.js"
            integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
            crossorigin="anonymous"
        ></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="wrapper">
    {% include 'includes/header.html' %}
    <div class="home">
        {% for instance in instances %}
        <a href="{%  url 'products:edit_product' id=instance.id  %}">
            <div class="card" style="width: 18rem">
                <img class="card-img-top" src="{{instance.image.url}}" alt="Card image cap" />
                <div class="card-body">
                    <h4 class="card-title">{{instance.name}}</h4>
                    <h6 class="card-text">INR{{instance.price}}</h6>
                    {% if not request.user.is_staff %}
                    <a
                        href="{% url 'products:add_to_cart'  id=instance.id %}"
                        class="btn btn-primary"
                        >Add to cart</a
                    >
                    {% endif %} {% if request.user.is_staff %}
                    <a
                        href="{% url 'products:delete_product' id=instance.id %}"
                        class="btn btn-danger action-button reload"
                        data-text="Are you sure want to remove this post. You can't undo this action."
                        data-title="Confirm Delete!"
                        title="Delete!"
                        >Delete</a
                    >
                    {% endif %}
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}