online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('users/', include("users.urls", namespace="users")),
    path('products/', include("products.urls", namespace="products")),

    
    
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)


    )

users/urls.py
from users import views
from django.urls import path


app_name = "users"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('admin-login/', views.admin_login, name="admin_login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),

]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path('admin-view/', views.admin_view, name="admin_view"),

]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password']
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Enter password"})
        }

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")

        if User.objects.filter(username=username).exists():
            self.add_error("username", "Username already exists")

users/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render,reverse
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.contrib.auth.models import User
from users.forms import UserForm


# Login functionality
def admin_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_staff:
                auth_login(request, user)

                return HttpResponseRedirect("/")

        context = {
            "title": "Login",
            "error": True,
            "message": "Invalid username or password"
        }
        return render(request, "users/login.html", context)
    else:
        context = {
            "title": "Login",

        }
        return render(request, "users/login.html", context)

#logout functionality
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))
# Login functionality
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)

                return HttpResponseRedirect("/")

        context = {
            "title": "Login",
            "error": True,
            "message": "Invalid username or password"
        }
        return render(request, "users/login.html", context)
    else:
        context = {
            "title": "Login",

        }
        return render(request, "users/login.html", context)

#logout functionality
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))

# signup functionality
def signup(request):

    if request.method == 'POST':
        
        form=UserForm(request.POST)
        if form.is_valid():
                first_name=form.cleaned_data["first_name"]
                password=form.cleaned_data["password"]
                username=form.cleaned_data["username"]
                user = User.objects.create_user(username=username, first_name=first_name, password=password)
                user.save()
                context = {
                    "message": "account created successfully",
                    "title": "TechiesPark| Registration"
                }
                return render(request, 'users/login.html', context=context)
                
        else:
                context = {
                    "title": "OnlineStore| Registration",
                    "form": form,
                }
                return render(request, 'users/registration.html', context)

    else:
        form=UserForm()
        context = {
            "title": "OnlineStore| Registration",
            "form": form,
        }
    return render(request, 'users/registration.html', context)

templates/users/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="wrapper">
    {% include 'includes/header.html' %}
    <div class="container">
        <form action="/users/login/" method="post">
            {% csrf_token %}
            <label for="">User Name</label><br />
            <input
                type="text"
                value=""
                placeholder="Phone Number"
                name="username"
                required
                class="form-control"
            />
            <label for="">Password</label><br />
            <div class="password">
                <input
                    type="password"
                    value=""
                    placeholder="Password"
                    name="password"
                    required
                    class="form-control"
                />
            </div>
            {%if error %}
            <p class="error" style="color: red">{{message}}</p>
            {% endif %} {% if message %}
            <small>{{message}}</small>
            {% else %}
            <p class="register">
                Don't have account <a href="{% url 'users:signup' %}">Register</a>
            </p>
            {% endif %}
            <button type="submit" class="btn btn-success">Log In</button>
        </form>
    </div>
</div>

{% endblock %}

templates/users/registration.html
{% extends 'base.html' %} {% load static %} {% block content %}{% include 'includes/header.html' %}
<div class="container">
    <h1 style="text-align: center">Register here</h1>
    <form
        action="{% url 'users:signup' %}"
        method="post"
        style="display: flex; flex-direction: column; width: 60%; margin: 0 auto"
    >
        {% csrf_token %}
        <label for="{{form.first_name.id_for_label}}">{{form.first_name.label}}</label>
        {{form.first_name}}
        <label for="{{form.email.id_for_label}}">{{form.email.label}}</label>
        {{form.email}}
        <label for="{{form.username.id_for_label}}">{{form.username.label}}</label>
        {{form.username}} {% for error in form.username.errors %}
        <small style="color: red">{{ error }}</small>
        {% endfor %}
        <label for="{{form.password.id_for_label}}">{{form.password.label}}</label>
        {{form.password}} {% for error in form.password.errors %}
        <small style="color: red">{{ error }}</small>
        {% endfor %}
        <input class="btn btn-primary mt-3" type="submit" value="Submit" />
    </form>
</div>

{% endblock %}